blank_issues_enabled: true
contact_links:
  - name: Bitcoin Core Security Policy
    url: https://github.com/novacoin/novacoin/blob/master/SECURITY.md
    about: View security policy
  - name: Bitcoin Core Developers
    url: https://novacoincore.org
    about: Bitcoin Core homepage
